### ISSUE TITLE
Build a new master on top of Version 4.0

### ISSUE THREAD

**Issue by daniellienert** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#188]
In order to `replace` the master and remain as much commit information as possible I would propose the following:

Adjust the 3.0 Version to fit to current master:

- [x] Change code structure to PSR-4 (https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/189)
- [x] Branch a 4.0
- [x] Adjust namespaces to Neos 3.0

Do the merge:

- [x] Do a merge into master (`git merge -X theirs 4.0`)
- [x] Diff the changes of the result to 4.0 and make it working.

**Comment by aertmann** [comment]
You mean on top of Version 3.0 right?

**Comment by daniellienert** [comment]
No *4.0* is correct (added the missing step in the list). The current master already has the namespace changes applied. 3.0 should be compatible to Neos 2.3. The namespace change then makes the 4.0. Which is then as close as it can get to the current master.

**Comment by aertmann** [comment]
Okay a bit confusing still tbh., but probably the right way. Is this a correct understanding? master needs changes that haven't been upmerged from 3.0 due to master already being migrated to the new namespace. Additionally update master to PSR-4. And release a 4.0 version based on master.

Also instead of branching a 4.0, consider using a branch alias for the master branch making it 4.0 until a 5.0 version needs to exist. All external core packages recently changed to being done like that to avoid a version branch and master being identical. Example https://github.com/neos/neos-seo/blob/master/composer.json#L18-L20. Only master should ever have a branch alias.

**Comment by kdambekalns** [comment]
Sounds like a plan!

**Comment by kdambekalns** [comment]
But we could skip the 4.0 branch for the time being, and use a branch-alias until we need to branch a new major…
