### ISSUE TITLE
Migration 20200513223401 creates wrong result

### ISSUE THREAD

**Issue by kdambekalns** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#367]
After running this migration, I see `_hiddenInIndex` being replaced by `neosneos_hidden_in_index`:

<img width="246" alt="Screenshot 2021-01-28 at 20 15 41" src="https://user-images.githubusercontent.com/95873/106187261-a9ba7780-61a5-11eb-88ee-6bcca41e661a.png">

It should result in `neos_hidden_in_index`, though.

Update: And `__parentPath` becomes `neos_parent_path ` (with a trailing space!)

**Comment by kitsunet** [comment]
This whole migration is way to aggressive. it just turend a customer instance into totally broken, because also a `.children([_hidden = true])` was changed as well has a something_something_hidden in their own package sql migrations and ORM index annotations. I would actually say we should remove this migration as the _useful_ case is definitely rarer IMHO than the "wrong" case.

**Comment by daniellienert** [comment]
Hey guys, sorry for that. Thats really bad. Lets remove it. I'd supply a patch.
